#!/bin/bash
waybar &
WOB_FILE=/tmp/hikari_sock.wob
if test -f "$WOB_FILE"; then
    rm $WOB_FILE
fi
mkfifo $WOB_FILE && tail -f $WOB_FILE | wob &
mako &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
