#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "molokai"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    relativenumber = 0
    filemanager = 'defx'
    autocomplete_method = 'coc'

    # Call bootstrap function 
    bootstrap_after = "myspacevim#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'lang#xml'

[[layers]]
  name = "lang#c"
  clang_executable = "/usr/bin/clang"
  clang_flags = ['-Wno-missing-field-initializers']
  [layer.clang_std]
    c = "c11"
    cpp = "c++1z"
    objc = "c11"
    objcpp = "c++1z"


[[layers]]
name = "git"
git-plugin = 'fugitive'

[[custom_plugins]]
name = 'google/vim-searchindex'

[[custom_plugins]]
name = "vim-scripts/dbext.vim"

[[custom_plugins]]
name = "python-mode/python-mode"

[[layers]]
name = "lsp"
  filetypes = [
    "rust",
    "javascript",
    "python",
  ]

[[custom_plugins]]
name = "numirias/semshi"

[[custom_plugins]]
name = "rhysd/git-messenger.vim"

